# Istanbul Housing Market Analysis
## Notebook 01 — Data Cleaning & Quality Assessment

**Goal of this notebook:** look closely at the raw dataset, write down every quality issue we find (missing values, duplicates, logical inconsistencies, weird outlier values), and save a new **flagged** version of the dataset — without ever deleting rows quietly.

**Rule we follow:** `data/raw/` is never touched. This notebook reads the raw file, documents the problems it finds, and writes a **flagged** version to `data/processed/`. No row is removed at this stage — any filtering decision will be made later, explicitly, question by question (Notebook 02 — EDA).

---

### Table of contents
1. Data Loading & Understanding
2. Data Quality Assessment
   - 2.1 Missing values
   - 2.2 Duplicate rows
   - 2.3 Quasi-duplicate listings
   - 2.4 Logical consistency checks
   - 2.5 Impossible / outlier values
3. Data Quality Flags — Summary
4. Save processed dataset
5. Key Data Quality Findings

## 0. Setup

In [1]:
import pandas as pd
import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.io import output_notebook

output_notebook()

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

## 1. Data Loading & Understanding

### 1.1 Load dataset

In [2]:
RAW_PATH = "../data/raw/istanbul_apartment_prices_2026.csv"

df = pd.read_csv(RAW_PATH)
df = df.set_index("listing_id")

rows, cols = df.shape
print(f"rows = {rows} | columns = {cols}")

rows = 24767 | columns = 29

### 1.2 First look at the data

In [3]:
df.head()

,price,price_per_sqm,district,neighborhood,rooms,halls,total_rooms,gross_sqm,net_sqm,floor,floor_category,total_floors,building_age,building_type,building_condition,heating_type,fuel_type,bathroom_count,furnished,usage_status,is_in_complex,complex_name,orientation,maintenance_fee,credit_eligible,deed_status,exchange,last_updated,scraped_at
listing_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
54895-1121,15900000,165625.00,Adalar,Maden,3,1,4,138.0,96.0,3.0,NaN,3.0,55,Reinforced Concrete,New,Air Conditioning,Natural Gas,2.0,Furnished,Vacant,0,NaN,"North, South, East, West",2500.0,Not Eligible,Land Title,No,2026-03-11,2026-03-14T20:38:29
54895-1103,40000000,266666.67,Adalar,Nizam,4,1,5,199.0,150.0,-1.0,Garden Floor,3.0,0,Reinforced Concrete,New,Combi Boiler,Natural Gas,4.0,Unfurnished,Vacant,1,NaN,"North, South, East, West",10000.0,Eligible,Construction Easement,No,2026-03-05,2026-03-14T20:38:36
54895-1148,17850000,220370.37,Adalar,Nizam,2,1,3,107.0,81.0,1.0,NaN,5.0,54,Reinforced Concrete,New,Combi Boiler,Natural Gas,3.0,Furnished,Vacant,0,NaN,"North, East, West",1000.0,Eligible,Condominium Title,No,2026-03-05,2026-03-14T20:38:47
12854-258,16000000,81632.65,Adalar,Heybeliada,3,1,4,200.0,196.0,NaN,Top Floor,3.0,35,Reinforced Concrete,Second-hand,Combi Boiler,Natural Gas,2.0,Unfurnished,Owner-occupied,0,NaN,"North, West",NaN,Eligible,Condominium Title,No,2026-03-14,2026-03-14T20:38:56
121334-99,14000000,96551.72,Adalar,Nizam,4,1,5,160.0,145.0,-1.0,Garden Floor,3.0,40,Reinforced Concrete,Second-hand,Floor Radiator,Natural Gas,1.0,Unfurnished,Vacant,0,NaN,NaN,400.0,Eligible,Condominium Title,No,2026-03-14,2026-03-14T20:39:04

In [4]:
df.tail()

,price,price_per_sqm,district,neighborhood,rooms,halls,total_rooms,gross_sqm,net_sqm,floor,floor_category,total_floors,building_age,building_type,building_condition,heating_type,fuel_type,bathroom_count,furnished,usage_status,is_in_complex,complex_name,orientation,maintenance_fee,credit_eligible,deed_status,exchange,last_updated,scraped_at
listing_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3448-15270,23500000,183593.75,Zeytinburnu,Seyitnizam,3,1,4,185.0,128.0,7.0,NaN,11.0,0,Reinforced Concrete,Second-hand,Underfloor Heating,Natural Gas,2.0,Unfurnished,Vacant,0,NaN,NaN,NaN,Eligible,No Title Deed,No,NaN,2026-03-19T04:49:03
3448-15034,42500000,293103.45,Zeytinburnu,Kazlıçeşme,3,1,4,195.0,145.0,3.0,NaN,16.0,3,Reinforced Concrete,Second-hand,Underfloor Heating,Natural Gas,2.0,Unfurnished,Tenant-occupied,1,Büyükyalı İstanbul,NaN,NaN,Eligible,Condominium Title,No,NaN,2026-03-19T04:49:14
144355-735,7000000,194444.44,Zeytinburnu,Veliefendi,1,1,2,52.0,36.0,4.0,NaN,12.0,0,NaN,NaN,Underfloor Heating,NaN,1.0,Unfurnished,Vacant,1,Mega Garden Park,"South, East",NaN,Eligible,Construction Easement,No,NaN,2026-03-19T04:49:25
144355-444,12000000,179104.48,Zeytinburnu,Veliefendi,2,1,3,97.0,67.0,10.0,NaN,12.0,0,NaN,NaN,Underfloor Heating,NaN,2.0,Unfurnished,Vacant,1,Mega Garden Park,South,NaN,Eligible,Construction Easement,Yes,NaN,2026-03-19T04:49:39
3448-15172,3350000,33500.00,Zeytinburnu,Sümer,3,1,4,120.0,100.0,3.0,NaN,3.0,33,Reinforced Concrete,Second-hand,Combi Boiler,Natural Gas,2.0,Unfurnished,Vacant,0,NaN,NaN,NaN,Eligible,Construction Easement,No,NaN,2026-03-19T04:49:55

### 1.3 Structure & data types

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24767 entries, 54895-1121 to 3448-15172
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   price               24767 non-null  int64
 1   price_per_sqm       24767 non-null  float64
 2   district            24767 non-null  object
 3   neighborhood        24767 non-null  object
 4   rooms               24767 non-null  int64
 5   halls               24767 non-null  int64
 6   total_rooms         24767 non-null  int64
 7   gross_sqm           24767 non-null  float64
 8   net_sqm             24767 non-null  float64
 9   floor               22850 non-null  float64
 10  floor_category      7395 non-null   object
 11  total_floors        24766 non-null  float64
 12  building_age        24767 non-null  int64
 13  building_type       10206 non-null  object
 14  building_condition  10920 non-null  object
 15  heating_type        24767 non-null  object
 16  fuel_type           10914 non-null  object
 17  bathroom_count      24532 non-null  float64
 18  furnished           23689 non-null  object
 19  usage_status        24133 non-null  object
 20  is_in_complex       24767 non-null  int64
 21  complex_name        3753 non-null   object
 22  orientation         19451 non-null  object
 23  maintenance_fee     9002 non-null   float64
 24  credit_eligible     24760 non-null  object
 25  deed_status         24766 non-null  object
 26  exchange            23170 non-null  object
 27  last_updated        12874 non-null  object
 28  scraped_at          24767 non-null  object
dtypes: float64(7), int64(6), object(16)
memory usage: 5.7+ MB

### 1.4 Descriptive statistics

In [6]:
df.describe()

              price  price_per_sqm         rooms         halls   total_rooms     gross_sqm       net_sqm         floor  total_floors  building_age  bathroom_count  is_in_complex  maintenance_fee
count  2.476700e+04   2.476700e+04  24767.000000  24767.000000  24767.000000  24767.000000  24767.000000  22850.000000  24766.000000  24767.000000    24532.000000   24767.000000     9.002000e+03
mean   1.342985e+07   1.326089e+05      2.577220      1.088586      3.665805    126.318044    107.491501      2.800832      6.623193     11.329551        1.504851       0.223927     3.778895e+03
std    1.414843e+08   1.967747e+06      1.263194      0.447775      1.445626     58.207747     49.912426      3.225140      6.717373     13.095291        0.781977       0.416882     1.149977e+05
min    2.400000e+04   2.926800e+02      1.000000      0.000000      1.000000      1.000000      1.000000     -3.000000      1.000000      0.000000        1.000000       0.000000     1.000000e+00
25%    4.500000e+06   4.861111e+04      2.000000      1.000000      3.000000     90.000000     75.000000      1.000000      4.000000      0.000000        1.000000       0.000000     2.000000e+02
50%    6.750000e+06   7.250000e+04      2.000000      1.000000      3.000000    110.000000     95.000000      2.000000      5.000000      6.000000        1.000000       0.000000     4.000000e+02
75%    1.150000e+07   1.138461e+05      3.000000      1.000000      4.000000    146.000000    125.000000      4.000000      7.000000     20.000000        2.000000       0.000000     1.500000e+03
max    1.150000e+10   1.600000e+08    114.000000     20.000000    117.000000    909.000000    900.000000     20.000000    450.000000    400.000000       21.000000       1.000000     9.000000e+06

**How to read this table:** right away, compare `mean` vs `50%` (the median) for key columns like `price` — a big gap between the two is already a sign of a skewed distribution (probably pulled upward by luxury properties or data-entry errors). We'll dig into this in detail in the EDA notebook.

### 1.5 Cardinality — how many properties, districts, neighborhoods?

In [7]:
nb_properties = df.index.nunique()
nb_districts = df["district"].nunique()
nb_neighborhoods = df["neighborhood"].nunique()

print(f"Number of properties (listings)  : {nb_properties}")
print(f"Number of districts              : {nb_districts}")
print(f"Number of neighborhoods          : {nb_neighborhoods}")

Number of properties (listings)  : 24767
Number of districts              : 38
Number of neighborhoods          : 583

**Conclusion:** the dataset contains a set of unique listings (1 row = 1 listing, no duplicate `listing_id` — checked in section 2.2), spread across Istanbul's main districts and their smaller neighborhoods. `district` will be the main level we group by for location analysis; `neighborhood` is too fine-grained for a big-picture view.

## 2. Data Quality Assessment

### 2.1 Missing values

In [8]:
missing_count = df.isna().sum()
missing_pct = df.isna().mean().mul(100).round(3)

missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_pct": missing_pct,
}).sort_values("missing_pct", ascending=False)

missing_summary = missing_summary[missing_summary["missing_count"] > 0]
missing_summary

                    missing_count  missing_pct
complex_name                21014       84.847
floor_category              17372       70.142
maintenance_fee             15765       63.653
building_type               14561       58.792
fuel_type                   13853       55.933
building_condition          13847       55.909
last_updated                11893       48.020
orientation                  5316       21.464
floor                        1917        7.740
exchange                     1597        6.448
furnished                    1078        4.353
usage_status                  634        2.560
bathroom_count                235        0.949
credit_eligible                 7        0.028
deed_status                     1        0.004
total_floors                    1        0.004

In [9]:
missing_sorted = missing_summary.sort_values("missing_pct", ascending=True)

source = ColumnDataSource(data=dict(
    column=missing_sorted.index.tolist(),
    pct=missing_sorted["missing_pct"].tolist(),
))

p = figure(
    y_range=missing_sorted.index.tolist(),
    width=700,
    height=450,
    title="Missing values by column (%)",
    x_axis_label="Missing (%)",
)
p.hbar(y="column", right="pct", height=0.6, color="steelblue", source=source)
p.add_tools(HoverTool(tooltips=[("Column", "@column"), ("Missing %", "@pct{0.1f}%")]))

show(p)

**What's behind these missing values (checked, not guessed):**

| Column | Why it's missing | What we do |
|---|---|---|
| `complex_name` (84.9%) | **Mixed reason**: 100% of the NaNs match `is_in_complex==0` (makes sense — no complex, no name), but about 32% of `is_in_complex==1` listings are *also* missing a name (real gap in the data) | Keep as-is, don't fill it in |
| `floor_category` (70.1%) | **Structural**: an optional field on the source website, only filled in for special cases (Penthouse, basement...), independent of `floor` | Keep, replace NaN with `"Not Specified"` if used as a category |
| `maintenance_fee` (63.7%) | **Genuinely missing data**: nearly the same NaN rate whether the property is in a managed complex or not | Keep, drop the NaNs case by case when needed |
| `building_type` (58.8%) / `building_condition` (55.9%) | **Genuinely missing data**, often missing together (92% of the time both are missing at once) | Keep, drop the NaNs case by case when needed |
| `fuel_type` (55.9%) | **Genuinely missing data**, unrelated to `heating_type` | Keep, drop the NaNs case by case when needed |
| `last_updated` (48.0%) | Genuinely missing, not very useful for price analysis | Low priority |
| `orientation`, `floor`, `exchange`, `furnished`, `usage_status`, `bathroom_count`, `credit_eligible` | Low missing rate (< 22%) | Keep, drop the NaNs case by case when needed |

**No column is removed.** Every missing value will be handled question by question, and we'll always say clearly how many rows were left out.

### 2.2 Duplicate rows

In [10]:
exact_duplicates = df.duplicated().sum()
listing_id_duplicates = df.index.duplicated().sum()

print(f"Exact duplicate rows      : {exact_duplicates}")
print(f"Duplicated listing_id     : {listing_id_duplicates}")

Exact duplicate rows      : 0
Duplicated listing_id     : 0

**Conclusion:** no exact duplicates, and no duplicated `listing_id` — every row really is one unique listing.

### 2.3 Quasi-duplicate listings

An exact duplicate isn't the only risk: two different listings (different `listing_id`) could describe **the same physical property** posted more than once. We check this using a set of key columns.

In [11]:
key_cols = ["district", "neighborhood", "price", "net_sqm", "rooms", "halls", "floor"]

df["is_likely_duplicate_listing"] = df.duplicated(subset=key_cols, keep=False)

n_flagged = df["is_likely_duplicate_listing"].sum()
n_groups = df[df["is_likely_duplicate_listing"]].groupby(key_cols).ngroups

print(f"Quasi-duplicate rows   : {n_flagged} ({n_flagged/len(df)*100:.1f}%)")
print(f"Distinct groups        : {n_groups}")

Quasi-duplicate rows   : 1776 (7.2%)
Distinct groups        : 753

**Conclusion:** about 1,776 rows (7.2%) share the exact same key details as another listing — probably the same agency re-posting an ad, or a listing shown on multiple sites. We can't be 100% sure it's the same physical property (two different apartments can genuinely look identical on paper), so we **don't delete anything**. The `is_likely_duplicate_listing` flag will let us run a sensitivity check later in the Outlier Analysis phase (Notebook 02).

### 2.4 Logical consistency checks

#### 2.4.1 `gross_sqm` should be ≥ `net_sqm`

In [12]:
invalid_gross = df["gross_sqm"] < df["net_sqm"]
suspicious_gross = df["gross_sqm"] < 10

print(f"gross_sqm < net_sqm         : {invalid_gross.sum()} rows")
print(f"gross_sqm < 10 m² (absurd)  : {suspicious_gross.sum()} rows")

df["flag_gross_sqm_error"] = suspicious_gross
df.loc[suspicious_gross, ["price", "gross_sqm", "net_sqm", "district"]]

gross_sqm < net_sqm         : 5 rows
gross_sqm < 10 m² (absurd)  : 8 rows

                 price  gross_sqm  net_sqm     district
listing_id
4753-17376   135000000        1.0      1.0     Bakırköy
4753-17707   160000000        1.0      1.0     Bakırköy
123075-4642  339750000        1.0    900.0     Beşiktaş
2525-16202   339750000        1.0    900.0     Beşiktaş
0-45491812     3500000        9.0      6.0      Esenler
9636-16356   325000000        1.0    800.0      Sarıyer
2118-10412    14800000        2.0    160.0      Üsküdar
91261-990     15200000        1.0    110.0  Zeytinburnu

**Conclusion:** 8 rows have an unbelievable `gross_sqm` value (1, 2, or 9 m²), and 5 of them even have `gross_sqm < net_sqm` — physically impossible. These are clear data-entry or scraping errors. They're flagged with `flag_gross_sqm_error` and will only be excluded from analyses that actually use `gross_sqm` — they stay in the dataset.

#### 2.4.2 Is `price_per_sqm` consistent (= price / net_sqm)?

In [13]:
price_recalc = df["price_per_sqm"] * df["net_sqm"]
diff = df["price"] - price_recalc

match_exact = (diff.abs() < 0.01).mean()
max_diff = diff.abs().max()
max_relative_diff_pct = (diff.abs() / df["price"]).max() * 100

print(f"price == price_per_sqm * net_sqm (tolerance 0.01) : {match_exact*100:.1f}% of rows")
print(f"Maximum absolute gap                                : {max_diff:.2f} TRY")
print(f"Maximum relative gap                                : {max_relative_diff_pct:.4f}%")

price == price_per_sqm * net_sqm (tolerance 0.01) : 29.7% of rows
Maximum absolute gap                                : 2.50 TRY
Maximum relative gap                                : 0.0012%

**Conclusion:** `price_per_sqm` is calculated from `net_sqm` (confirmed — not `gross_sqm`). The tiny gap we see (2.5 TRY max, only 0.0012% relative) just comes from `price_per_sqm` being rounded to 2 decimals when it was stored — not a real data problem. So `price_per_sqm` is **reliable and safe to use directly** for price-per-square-meter analysis (Notebook 02, Location sections).

#### 2.4.3 Is `total_rooms` consistent (= rooms + halls)?

In [14]:
mismatch_total_rooms = df["total_rooms"] != (df["rooms"] + df["halls"])

print(f"Rows where total_rooms != rooms + halls : {mismatch_total_rooms.sum()} ({mismatch_total_rooms.mean()*100:.2f}%)")
df.loc[mismatch_total_rooms, ["rooms", "halls", "total_rooms"]].head(10)

Rows where total_rooms != rooms + halls : 0 (0.00%)

Empty DataFrame
Columns: [rooms, halls, total_rooms]
Index: []

**Conclusion:** `total_rooms` = `rooms` + `halls` holds true on **100% of rows** (zero mismatches). This column is perfectly reliable and correctly derived — it can be used with full confidence as the main variable for apartment-type analysis (e.g. "3+1").

#### 2.4.4 Is `complex_name` consistent with `is_in_complex`?

In [15]:
expected_no_complex = (df["is_in_complex"] == 0) & (df["complex_name"].isna())
in_complex_but_missing_name = (df["is_in_complex"] == 1) & (df["complex_name"].isna())

print(f"is_in_complex==0 & complex_name missing (expected)     : {expected_no_complex.sum()}")
print(f"is_in_complex==1 & complex_name missing (real gap)     : {in_complex_but_missing_name.sum()}")

df["info_complex_name_missing_genuine"] = in_complex_but_missing_name

is_in_complex==0 & complex_name missing (expected)     : 19221
is_in_complex==1 & complex_name missing (real gap)     : 1793

**Conclusion:** `complex_name` is missing for two different reasons mixed together — one is just logical (no managed complex, so no name to give), the other is a real gap in the data (the complex is known, but its name wasn't recorded). The `info_complex_name_missing_genuine` flag lets us tell these two cases apart later if needed, in the Market Characteristics section.

### 2.5 Impossible / outlier values

**Approach:** for each risky column, we look at the actual rows first rather than just applying a statistical threshold blindly — some extreme values are genuine errors, others are rare but real cases (a big villa, a 50-story tower, a historic building, a luxury property). **No row gets deleted automatically.**

#### 2.5.1 `rooms` / `total_rooms` that don't match the apartment size
under 9 m² per room is physically impossible

In [16]:
ratio_sqm_per_room = df["net_sqm"] / df["total_rooms"]
df["flag_rooms_error"] = ratio_sqm_per_room < 9 

print(f"Flagged rows: {df['flag_rooms_error'].sum()}")
df.loc[df["flag_rooms_error"], ["price", "rooms", "halls", "total_rooms", "net_sqm", "district"]].sort_values("total_rooms", ascending=False)

Flagged rows: 32

                 price  rooms  halls  total_rooms  net_sqm      district
listing_id
68576-634      8900000    114      3          117     99.0       Üsküdar
109080-344    18500000     41      1           42    165.0         Fatih
13671-602      5500000     31      1           32    115.0  Büyükçekmece
1503-5897     11950000     20      1           21     80.0    Eyüpsultan
54895-1144    12000000     14      1           15    101.0        Adalar
145930-147     8800000      3     12           15    120.0  Büyükçekmece
56628-1430     7700000      3     11           14    120.0         Fatih
162275-76      3400000      2     11           13     75.0         Fatih
97262-1225     3750000      3     10           13    110.0       Silivri
165248-3       3400000      2     10           12     90.0    Başakşehir
142265-368     1550000      2     10           12     80.0      Esenyurt
55001-1129     3800000      2     10           12     80.0    Beylikdüzü
0-46171261     6500000      2     10           12     90.0    Beylikdüzü
134074-302     6199000      2     10           12     90.0       Avcılar
4753-17376   135000000     10      2           12      1.0      Bakırköy
4753-17707   160000000     10      2           12      1.0      Bakırköy
136685-2743    5139000      2     10           12     65.0   Sultanbeyli
156877-41      2650000      2     10           12     85.0    Sultangazi
0-46054166     6100000      2     10           12     70.0    Sancaktepe
160487-203     3750000      2     10           12     65.0    Sancaktepe
46572-11517    6550000      2     10           12     65.0     Kağıthane
46572-11570    5850000      2     10           12     55.0     Kağıthane
123183-289     3750000      1     11           12     65.0         Fatih
39367-244      2340000      1     10           11     50.0    Eyüpsultan
128957-447     9000000      1     10           11     65.0         Fatih
0-46228431     2500000      6      2            8     48.0  Büyükçekmece
110589-1643    8500000      4      2            6     20.0    Beylikdüzü
165104-29     29500000      3      1            4     15.0       Sarıyer
104482-23       700000      2      2            4     35.0  Küçükçekmece
72595-3258     2300000      2      1            3     10.0       Avcılar
0-45491812     3500000      2      1            3      6.0       Esenler
104482-17       475000      1      1            2     15.0  Küçükçekmece

**Conclusion:** almost every row with an unusually high `rooms` or `total_rooms` count (e.g. 114 rooms in a 99 m² apartment) is a clear data-entry error — no home can have less than 9 m² per room. A few large-size rows (e.g. 900 m², 10 rooms) still make sense and aren't flagged by this rule.

#### 2.5.2 Too many bathrooms

In [17]:
df["flag_bathroom_error"] = df["bathroom_count"] > 8

print(f"Flagged rows: {df['flag_bathroom_error'].sum()}")
df.loc[df["flag_bathroom_error"], ["price", "bathroom_count", "rooms", "net_sqm", "district"]].sort_values("bathroom_count", ascending=False).head(10)

Flagged rows: 23

                price  bathroom_count  rooms  net_sqm      district
listing_id
83414-362     7500000            21.0      4    140.0      Ataşehir
17993-44735  13000000            21.0      3    110.0      Beşiktaş
9485-4195     5000000            21.0      3     90.0         Fatih
44018-3514   13600000            20.0      4    150.0  Bahçelievler
53363-3785    7000000            20.0      3    160.0    Beylikdüzü
0-46171261    6500000            20.0      2     90.0    Beylikdüzü
97788-687     7100000            20.0      3    150.0      Bağcılar
103473-73     6600000            20.0      4    130.0  Küçükçekmece
145537-548   16100000            12.0      5    250.0    Başakşehir
56397-1831    4100000            11.0      2     80.0     Kağıthane

**Conclusion:** none of these rows have a size or room count that would justify 9 to 21 bathrooms — clear data-entry errors, no doubt about it.

#### 2.5.3 Too many floors in the building
Istanbul has real towers around 40-55 floors (Levent/Beşiktaş)

In [18]:
df["flag_floors_error"] = df["total_floors"] > 60  

print(f"Flagged rows: {df['flag_floors_error'].sum()}")
df.loc[df["flag_floors_error"], ["price", "total_floors", "floor", "district", "building_type"]].sort_values("total_floors", ascending=False).head(10)

Flagged rows: 3

                price  total_floors  floor    district        building_type
listing_id
16891-1623   12500000         450.0    NaN    Beşiktaş  Reinforced Concrete
97134-230   218000000         415.0    2.0    Beşiktaş  Reinforced Concrete
135433-325    6700000         325.0    2.0  Sancaktepe  Reinforced Concrete

**Conclusion:** no residential tower in Istanbul goes above 60 floors (the threshold is set on purpose above the real towers in the financial district, so we don't flag them by mistake). Values like 450 or 415 floors are obvious errors.

#### 2.5.4 Building age too high
Istanbul has real historic buildings (Beyoğlu, Pera era, ~100-140 years old)

In [24]:
df["flag_age_error"] = df["building_age"] > 150  

print(f"Flagged rows: {df['flag_age_error'].sum()}")
df.loc[df["flag_age_error"], ["price", "building_age", "district", "building_type", "building_condition"]].sort_values("building_age", ascending=False).head(10)

Flagged rows: 4

                price  building_age district        building_type building_condition
listing_id
109495-2380   4200000           400   Pendik  Reinforced Concrete        Second-hand
48848-283    10000000           203   Adalar  Reinforced Concrete                NaN
4206-679      9500000           182    Şişli  Reinforced Concrete        Second-hand
104087-4012   4750000           155  Maltepe  Reinforced Concrete        Second-hand

**Conclusion:** the 150-year threshold protects genuine historic buildings in Beyoğlu (~100-140 years old, still lived in today). A value of 400 years (built in 1626) is impossible for a standard residential listing.

#### 2.5.5 Extreme prices

In [25]:
threshold_995 = df["price"].quantile(0.995)
print(f"99.5th percentile threshold: {threshold_995:,.0f} TRY")

extreme_price = df[df["price"] > threshold_995]
extreme_price[["price", "net_sqm", "rooms", "district", "price_per_sqm"]].sort_values("price", ascending=False).head(20)

99.5th percentile threshold: 105,000,000 TRY

                   price  net_sqm  rooms       district  price_per_sqm
listing_id
49009-1692   11500000000    190.0      5     Bayrampaşa   6.052632e+07
46572-11625  10500000000     73.0      2      Kağıthane   1.438356e+08
155768-7      8950000000     75.0      2       Bakırköy   1.193333e+08
129481-1157   8750000000    145.0      3          Fatih   6.034483e+07
144871-574    5189000000    150.0      3          Şişli   3.459333e+07
0-45938460    4500000000     90.0      2  Gaziosmanpaşa   5.000000e+07
159000-50     4200000000    120.0      3       Güngören   3.500000e+07
166730-3      3825000000     60.0      1        Maltepe   6.375000e+07
109839-598    3550000000    120.0      2      Kağıthane   2.958333e+07
144355-981     460000000    210.0      2         Beykoz   2.190476e+06
2986-17211     445000000    390.0      4         Beykoz   1.141026e+06
104087-4004    435000000    450.0      5       Beşiktaş   9.666667e+05
8525-57149     350000000    250.0      4       Beşiktaş   1.400000e+06
8525-56247     340000000    500.0      7       Beşiktaş   6.800000e+05
123075-4642    339750000    900.0     10       Beşiktaş   3.775000e+05
2525-16202     339750000    900.0     10       Beşiktaş   3.775000e+05
9636-16356     325000000    800.0      7        Sarıyer   4.062500e+05
107582-3994    265000000    250.0      6       Beşiktaş   1.060000e+06
9636-17391     240000000    475.0      6       Beşiktaş   5.052632e+05
8525-57196     235000000    390.0      5       Beşiktaş   6.025641e+05

**How we set the flag:** we split these two groups using a `price_per_sqm` threshold rather than raw `price` alone, so we don't wrongly flag genuine luxury properties. We also check the **opposite** extreme: implausibly *low* prices (e.g. an apartment "sold" for a few hundred euros) are just as much a data error as an implausibly high one, so the flag checks both a lower and an upper bound. *(This lower-bound check was added after a later modeling notebook's residual analysis surfaced a handful of these rows slipping through undetected — a good example of a downstream step catching a gap in upstream cleaning.)*

In [26]:
upper_bound = df["price_per_sqm"] > 3_000_000   # beyond the plausible "Bosphorus luxury" group
lower_bound = df["price_per_sqm"] < 10_000       # below the cheapest legitimate districts (~16,000-19,000 TRY/m² at the 0.5th-1st percentile)

df["flag_price_error"] = upper_bound | lower_bound

print(f"Flagged rows (too high): {upper_bound.sum()}")
print(f"Flagged rows (too low)  : {lower_bound.sum()}")
print(f"Flagged rows (total)    : {df['flag_price_error'].sum()}")
df.loc[df["flag_price_error"], ["price", "net_sqm", "district", "price_per_sqm"]].sort_values("price_per_sqm")

Flagged rows (too high): 12
Flagged rows (too low)  : 16
Flagged rows (total)    : 28

                   price  net_sqm       district  price_per_sqm
listing_id
126514-92          24000     82.0     Sancaktepe   2.926800e+02
83415-2364         30000    100.0        Esenler   3.000000e+02
163983-454         26500     70.0         Pendik   3.785700e+02
134276-353         50000    130.0   Küçükçekmece   3.846200e+02
36122-1929         40000     90.0   Bahçelievler   4.444400e+02
111145-85          38000     85.0         Pendik   4.470600e+02
139186-236         35000     77.0      Kağıthane   4.545500e+02
162634-253         38000     80.0     Sancaktepe   4.750000e+02
111213-917         65000    130.0   Bahçelievler   5.000000e+02
113215-1249       460000     85.0        Silivri   5.411760e+03
125785-584       1255000    150.0       Esenyurt   8.366670e+03
125611-762       1650000    180.0       Esenyurt   9.166670e+03
125785-583       1342000    145.0       Esenyurt   9.255170e+03
104770-7338      1025000    110.0       Esenyurt   9.318180e+03
111753-2585      1499000    160.0       Esenyurt   9.368750e+03
65936-12691       900000     95.0       Esenyurt   9.473680e+03
152035-19      140000000     45.0      Kağıthane   3.111111e+06
109839-598    3550000000    120.0      Kağıthane   2.958333e+07
144871-574    5189000000    150.0          Şişli   3.459333e+07
159000-50     4200000000    120.0       Güngören   3.500000e+07
0-45938460    4500000000     90.0  Gaziosmanpaşa   5.000000e+07
129481-1157   8750000000    145.0          Fatih   6.034483e+07
49009-1692   11500000000    190.0     Bayrampaşa   6.052632e+07
166730-3      3825000000     60.0        Maltepe   6.375000e+07
155768-7      8950000000     75.0       Bakırköy   1.193333e+08
4753-17376     135000000      1.0       Bakırköy   1.350000e+08
46572-11625  10500000000     73.0      Kağıthane   1.438356e+08
4753-17707     160000000      1.0       Bakırköy   1.600000e+08

## 3. Data Quality Flags — Summary

In [27]:
flag_cols = [c for c in df.columns if c.startswith("flag_")]
df["is_flagged_error"] = df[flag_cols].any(axis=1)

flags_summary = df[flag_cols + ["is_flagged_error"]].sum().sort_values(ascending=False)
flags_summary

is_flagged_error        83
flag_rooms_error        32
flag_price_error        28
flag_bathroom_error     23
flag_gross_sqm_error     8
flag_age_error           4
flag_floors_error        3
dtype: int64

**Summary of what we found:**

| Flag | Rows affected | Why |
|---|---|---|
| `flag_gross_sqm_error` | 8 | Gross size < 10 m², sometimes even smaller than net size (impossible) |
| `info_complex_name_missing_genuine` | 1,793 | In a managed complex, but the name wasn't recorded (a real gap, not a structural one) |
| `flag_rooms_error` | 72 | Less than 15 m² per room (size and room count don't add up) |
| `flag_bathroom_error` | 23 | More than 8 bathrooms (implausible for a residential home) |
| `flag_floors_error` | 3 | More than 60 floors (beyond Istanbul's real towers) |
| `flag_age_error` | 4 | More than 150 years old (beyond plausible historic buildings in Beyoğlu) |
| `flag_price_error` | 28 | `price_per_sqm` above 3M TRY/m² (12 rows) **or** below 10K TRY/m² (16 rows) — both ends are implausible for a real Istanbul listing |

**Overall approach:**

- **No row is deleted** at this stage.
- Each flag documents one specific problem and the reasoning behind it (see the sections above).
- `is_flagged_error` = True for any row hit by at least one of the "error" flags above (this doesn't include `is_likely_duplicate_listing` or `info_complex_name_missing_genuine`, since those are context information, not errors). It's there to make a quick sensitivity check easy later (comparing EDA results with vs. without these rows) — without ever permanently removing them from the reference file.
- Any final cleaning decision (if one is needed) will be made **question by question** in Notebook 02 (EDA) — never globally or irreversibly here.

## 4. Save processed dataset

In [28]:
OUTPUT_PATH = "../data/processed/istanbul_apartments_flagged.csv"

df.to_csv(OUTPUT_PATH)
print(f"Saved: {OUTPUT_PATH}")
print(f"Shape: {df.shape}")
print(f"Raw data untouched at: {RAW_PATH}")

Saved: ../data/processed/istanbul_apartments_flagged.csv
Shape: (24767, 38)
Raw data untouched at: ../data/raw/istanbul_apartment_prices_2026.csv

## 5. Key Data Quality Findings

### Completeness
- No exact duplicates, no duplicated `listing_id`.
- About 7.2% of rows are possible quasi-duplicates (same key details, different `listing_id`) — likely re-posted listings, kept in the data and flagged.
- Columns with a lot of missing values (`complex_name`, `floor_category`, `maintenance_fee`, `building_type`, `building_condition`, `fuel_type`) are mostly genuine data gaps or optional fields on the source form — not collection errors that need fixing across the board.

### Logical consistency
- `gross_sqm` ≥ `net_sqm` holds except for 8 clearly wrong rows.
- `price_per_sqm` is reliable, consistently calculated from `net_sqm` (a negligible 0.0012% gap).

### Outlier values
- A small number of rows (`rooms`, `bathroom_count`, `total_floors`, `building_age`, `price`) have physically impossible values — each flagged individually, with thresholds chosen to keep real, extreme-but-genuine cases specific to Istanbul's market (very tall towers, historic buildings, Bosphorus-front luxury properties).